### ISSUE TITLE
Benchmarks comparing native go and Cgo based libraries

### ISSUE THREAD

**Issue by tariq1890** [fawick/speedtest-resize#15]
Hi @fawick,

Thanks for this great repository. I have been exploring many image processing solutions for Go and I was considering using libraries like gmagick, imagick etc. But when I had compared these libraries with gift, gift seemed to outperform all of them. (Running ImageMagick  and libvips in the command line was still the fastest, however). 

In your Readme.md, you've mentioned that the Cgo libraries outperform the native golang libraries. But you haven't included imagick or gmagick in any of the comparison tables. Could you share those results as well ?

**Comment by fawick** [comment]
Hi @tariq1890,

imagick and gmagick are already included in the comparisons done by me and @nono in the README as **ImageMagick_thumbnail**, **ImageMagick_resize**, and **GraphicsMagick_thumbnail**, using the *resize* and *thumbnail* algorithms of the libraries, respectively.

The general idea of the repository is to enable others to run their own benchmarks against exemplary images of their own, which will be more diagnostically conclusive than my numbers.

Closing this issue now.
