### ISSUE TITLE
How about Discord image compressing library?

### ISSUE THREAD

**Issue by crimist** [fawick/speedtest-resize#16]
https://blog.discordapp.com/how-discord-resizes-150-million-images-every-day-with-go-and-c-c9e98731c65d

https://github.com/discordapp/lilliput

**Comment by fawick** [comment]
Interesting idea, indeed. Would you be able to contribute a benchmark implementation?

**Comment by fawick** [comment]
@sys0x00 Would you kindly take a look at #18?

**Comment by syc0x00** [comment]
Ah sorry, looks good.

I'd assume you could make the output buffer the size of the input though since the compressed file shouldn't be bigger than the original.

```go
outputImg := make([]byte, origFileStat.Size())
```

You could add a 20% buffer to the length as well if you thought that it might be an issue.
