### ISSUE TITLE
Add go.image/draw

### ISSUE THREAD

**Issue by matrixik** [fawick/speedtest-resize#8]
Remainder to add `go.image/draw` when it will be added to https://code.google.com/p/go.image

https://codereview.appspot.com/101670045/

**Comment by fawick** [comment]
I plan to finally address this over the weekend. 

Note-to-self: https://godoc.org/golang.org/x/image/draw#Interpolator implements https://godoc.org/golang.org/x/image/draw#Scaler and for the speedtest I should add the predefined NearestNeighbor, at least

**Comment by matrixik** [comment]
Great, thank you.
